version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
      image: mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: mysql

volumes:
  mysql-data:
